### ISSUE TITLE
Issues with image uploading: UploadSiteHostedPictures

### ISSUE THREAD

**Issue by markskayff** [geekseller/ebay-sdk-php#1]
We are having an issue in production with uploading images using the **TradingTypes\UploadSiteHostedPicturesRequestType** type of request.

We are on:
PHP 7.4.3
Ubuntu 20.04 LTS

We are getting a ""XML Parse error." in the response. It's strange as nothing seem to have changed on our end.

Any ideas?

**Comment by markskayff** [comment]
More context on this error. See the file.
[Uploading ebay-api-error.txt…]()

**Comment by markskayff** [comment]
More context on this error.
See the file.
[ebay-api-error.txt](https://github.com/geekseller/ebay-sdk-php/files/6571998/ebay-api-error.txt)

**Comment by geekseller** [comment]
Hi @markskayff, we just wanted to let you know, we will not be able to look into this at the moment and we may need to abandon this SDK/repo. eBay is deprecating many old APIs which will affect this SDK.  See details at https://developer.ebay.com/docs/api-deprecation
